= Configuration

== Configuration properties

The following table contains configuration settings for the Hawtio core system and various Hawtio plugins.

[cols="2,1,5"]
|===
|System property |Default |Description

|`hawtio.sessionTimeout`
|-
|The maximum time interval, in seconds, that the servlet container will keep this session open between client accesses. If this option is not configured, then Hawtio uses the default session timeout of the servlet container.

|hawtio.proxyAllowlist
|`localhost, 127.0.0.1`
|Comma-separated allowlist for target hosts that Connect plugin can connect to via `ProxyServlet`. All hosts that are not listed in this allowlist are denied to connect for security reasons. This option can be set to `*` to allow all hosts. Prefixing an element of the list with `"r:"` allows to define a regexp (example: `localhost,r:myserver[0-9]+.mydomain.com`)

|hawtio.localAddressProbing
|`true`
|Whether local address probing for proxy allowlist is enabled or not upon startup. Set this property to `false` to disable it.

|hawtio.disableProxy
|`false`
|With this property set to `true`, `ProxyServlet` (`/hawtio/proxy/*`) can be disabled. This makes Connect plugin unavailable, which means Hawtio can no longer connect to remote JVMs, but sometimes users might want to do so because of security if Connect plugin is not used.

|hawtio.redirect.scheme
|-
|The scheme of the redirect URL to login page when authentication is required.
|===

== Jolokia AgentServlet

The Jolokia agent is deployed automatically with `io.hawt.web.JolokiaConfiguredAgentServlet` that extends Jolokia native `org.jolokia.http.AgentServlet` class, defined in `hawtio-war/WEB-INF/web.xml`.

To customize Jolokia Servlet configuration, according to the parameters that it supports and that are defined in the https://jolokia.org/reference/html/agents.html#agent-war-init-params[Jolokia documentation], you have to pass them as Java System properties prefixed with `jolokia.`. E.g.:

[source]
----
-Djolokia.policyLocation=file:///opt/hawtio/my-jolokia-access.xml
----

NOTE: The parameter `restrictorClass` is already used in `hawtio-war/WEB-INF/web.xml` to implement role-based access control (RBAC) for Jolokia invocations. If you want to use your own Jolokia restrictor, make sure to extend `io.hawt.web.RBACRestrictor` to implement your own restrictor class. Otherwise, part of Hawtio's RBAC functions will be lost.
