= Contributor Guide

== What do I need to know to help?

If you are looking to help to with a code contribution, our project uses TypeScript, React, and Java. If you don't feel ready to make a code contribution yet, no problem! You can also check out the https://github.com/hawtio/website/issues[documentation issues].

If you are interested in making a code contribution and would like to learn more about the technologies that we use, check out the list below:

- https://github.com/hawtio/hawtio-next/blob/main/docs/developing.md[Developing Hawtio.next]
- https://react.dev/[React]
- https://www.patternfly.org/[PatternFly]
- https://jolokia.org[Jolokia]
- https://docs.oracle.com/en/java/javase/11/jmx/java-management-extensions-jmx-user-guide.html[JMX]

== How do I make a contribution?

Never made an open source contribution before? Wondering how contributions work in our project? Here's a quick rundown:

. Find an issue that you are interested in addressing or a feature that you would like to add.
. Fork the repository associated with the issue to your local GitHub account.
. Clone your fork to your local machine using `git clone git://github.com/<your username>/<repository name>.git`.
. Add the Hawtio remote repository using `git remote add upstream git://github.com/hawtio/<repository name>.git`.
. Create a new branch for your fix using `git checkout -b <branch-name>`.
. Make the appropriate changes for the issue you are trying to address or the feature that you want to add.
. Commit your changes using a descriptive commit message that follows https://www.conventionalcommits.org/en/v1.0.0/[the commit message conventions].
. Push the changes to the remote repository using `git push origin <branch-name>`.
. Submit a pull request to the upstream repository.
. Title the pull request with a short description of the changes made and the issue or bug number associated with your change. For example, you can title an issue like so `"Added more log outputting to resolve #4352"`.
. In the description of the pull request, explain the changes that you made, any issues you think exist with the pull request you made, and any questions you have for the maintainer. It's OK if your pull request is not perfect (no pull request is), the reviewer will be able to help you fix any problems and improve it!
. Wait for the pull request to be reviewed by a maintainer.
. Make changes to the pull request if the reviewing maintainer recommends them.
. Celebrate your success after your pull request is merged!
