= Overview

This is the documentation for Hawtio v3. The old Hawtio v2 documentation is archived here: https://hawtio-v2.surge.sh/docs/

== xref:get-started.adoc[]

Read the getting started guide to find out how to download and install Hawtio in your own environment.

== Using Hawtio

=== xref:configuration.adoc[]

Read up on how to configure Hawtio in various environments, such as configuring security and where Hawtio stores stuff.

=== xref:plugins.adoc[]

Read an overview of the plugins available in Hawtio, including server-side and external dynamic plugins.
 
=== xref:keycloak.adoc[]

Read up on how you can integrate Hawtio with https://www.keycloak.org/[Keycloak] on various application containers.

== General Docs

=== xref:faq.adoc[]

Read commonly asked questions about the Hawtio project, including solutions to common problems getting started with Hawtio.

=== https://github.com/hawtio/hawtio/releases[Releases]

View the latest release details.

=== xref:contributing.adoc[]

Read how to get started building Hawtio and work with the code.

== Developers

=== https://github.com/hawtio/hawtio/blob/3.x/RELEASING.md[RELEASING]
