= Overview

This is the documentation for Hawtio v3. The old Hawtio v2 documentation is archived here: https://hawtio-v2.surge.sh/docs/

xref:overview-v3.adoc[]:: If you want to know what Hawtio v3 is, read this first.

xref:versions.adoc[]:: Check this page for the supported version matrix table of dependent technologies and components for each Hawtio version.

== xref:get-started.adoc[]

Read the getting started guide to find out how to download and install Hawtio in your own environment.

== Using Hawtio

=== xref:configuration.adoc[]

Read up on how to configure Hawtio in various environments, such as configuring security and where Hawtio stores stuff.

=== xref:plugins.adoc[]

Read an overview of the plugins available in Hawtio, including server-side and external dynamic plugins.
 
=== xref:keycloak.adoc[]

Read up on how you can integrate Hawtio with https://www.keycloak.org/[Keycloak] on various application containers.

== Using Hawtio on Kubernetes/OpenShift

=== xref:online/openshift.adoc[]

Read this page if you want to deploy Hawtio on OpenShift.

=== xref:online/kubernetes.adoc[]

Read this page if you want to deploy Hawtio on Kubernetes.

=== xref:online/create-user.adoc[]

This page explains how you can create a user when using Hawtio Online with the form-based authentication.

=== xref:online/generate-certificates.adoc[]

This page explains how you can manually generate the required certificates on your own.

=== xref:online/rbac.adoc[]

This page explains how RBAC works in Hawtio Online.

=== xref:online/develop.adoc[]

Read this page if you want to develop Hawtio Online.

== General Docs

=== xref:faq.adoc[]

Read commonly asked questions about the Hawtio project, including solutions to common problems getting started with Hawtio.

=== xref:releases.adoc[]

View the latest release details.

=== xref:contributing.adoc[]

Read how to get started building Hawtio and work with the code.

== Developers

=== xref:releasing.adoc[]

Link to the doc for how to release Hawtio.
