= Keycloak Integration

You can secure your Hawtio console with https://www.keycloak.org[Keycloak]. To integration Hawtio with Keycloak, you need to:

1. Prepare Keycloak server
2. Deploy Hawtio to your favourite runtime (Quarkus, Spring Boot, WildFly, Karaf, Jetty, Tomcat, etc.) and configure it to use Keycloak for authentication

== Prepare Keycloak server

Install and run Keycloak server. The easiest way is to use https://quay.io/repository/keycloak/keycloak[Docker image]:

[source,console]
----
docker run -d --name keycloak \
  -p 18080:8080 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  quay.io/keycloak/keycloak start-dev
----

Here we use port number `18080` for the Keycloak server to avoid potential conflicts with the ports other applications might use.

You can log in to the Keycloak admin console http://localhost:18080/admin/ with user `admin` / password `admin`. Import https://raw.githubusercontent.com/hawtio/hawtio/3.x/examples/keycloak-integration/hawtio-demo-realm.json[hawtio-demo-realm.json] into Keycloak. To do so, click `Create Realm` button and then import `hawtio-demo-realm.json`. It will create `hawtio-demo` realm.

The `hawtio-demo` realm has the `hawtio-client` application installed as a public client, and defines a couple of realm roles such as `admin` and `viewer`. The names of these roles are the same as the default Hawtio roles, which are allowed to log in to Hawtio admin console and to JMX.

There are also 3 users:

- `admin` with password `admin` and role `admin`, who is allowed to login into Hawtio
- `viewer` with password `viewer` and role `viewer`, who is allowed to login into Hawtio
- `jdoe` with password `password` and no role assigned, who is not allowed to login into Hawtio

NOTE: Currently, the difference in roles does not affect Hawtio access rights on Quarkus and Spring Boot, as Hawtio RBAC functionality is not yet implemented on those runtimes.

== Quarkus

== Spring Boot

Firstly, apply xref:get-started.adoc#_running_a_spring_boot_app[the required configuration] for attaching Hawtio to a Spring Boot app.

Next, add the following dependency to `pom.xml` (replace `x.y.z` with the latest Hawtio release version):

[source,xml]
----
<dependency>
  <groupId>io.hawt</groupId>
  <artifactId>hawtio-springboot-keycloak</artifactId>
  <version>x.y.z</version>
</dependency>
----

Then add the following lines in `application.properties` (which configures the server-side Keycloak adapter):

[source,java]
----
# Keycloak config
keycloak.realm=hawtio-demo
keycloak.resource=hawtio-client
keycloak.auth-server-url=http://localhost:18080/auth
keycloak.ssl-required=external
keycloak.public-client=true
keycloak.principal-attribute=preferred_username
----

Finally create `keycloak-hawtio.json` under `src/main/resources` in the Spring Boot project (which serves as the client-side Hawtio JS configuration):

[source,json]
----
{
  "realm": "hawtio-demo",
  "clientId": "hawtio-client",
  "url": "http://localhost:18080/auth",
  "ssl-required": "external",
  "public-client": true,
  "jaas": false
}
----

Build and run the project and it will be integrated with Keycloak. See https://github.com/hawtio/hawtio/tree/master/examples/springboot-keycloak[springboot-keycloak example] for a working example.

== Apache Karaf

Assume `$KARAF_HOME` is the root directory of your Karaf/Fuse installation.

Run Karaf/Fuse:

[source,console]
----
cd $KARAF_HOME/bin
./karaf
----

Replace `./karaf` with `./fuse` if you are on Red Hat Fuse.

Install Hawtio (replace `x.y.z` with the latest Hawtio release version):

[source,console]
----
feature:add-repo hawtio x.y.z
feature:install hawtio
----

Install https://github.com/ops4j/org.ops4j.pax.keycloak[pax-keycloak]:

[source,console]
----
feature:add-repo pax-keycloak
feature:install pax-keycloak
----

This automatically generates `keycloak-hawtio.json`, `keycloak-bearer.json`, and `keycloak-direct-access.json` files under `$KARAF_HOME/etc/`. It also updates `$KARAF_HOME/etc/system.properties` with the following system properties:

[source,java]
----
# Hawtio / Keycloak integration
hawtio.keycloakEnabled = true
hawtio.roles = admin,manager,viewer
hawtio.realm = karaf
hawtio.keycloakClientConfig = file://${karaf.etc}/keycloak-hawtio.json
hawtio.rolePrincipalClasses=org.keycloak.adapters.jaas.RolePrincipal,org.apache.karaf.jaas.boot.principal.RolePrincipal
----

Replace them with `keycloak-hawtio.json`, `keycloak-bearer.json`, and `keycloak-direct-access.json` in https://github.com/hawtio/hawtio/tree/master/examples/keycloak-integration[this example]. File `keycloak-bearer.json` is currently used for adapters on server (JAAS Login module) side. File `keycloak-hawtio.json` is used on client (Hawtio JS application) side. File `keycloak-direct-access.json` is not used but the realm name needs to be updated.

[source,console]
----
cp examples/keycloak-integration/keycloak-hawtio.json $KARAF_HOME/etc/
cp examples/keycloak-integration/keycloak-bearer.json $KARAF_HOME/etc/
cp examples/keycloak-integration/keycloak-direct-access.json $KARAF_HOME/etc/
----

Restart Karaf/Fuse.

Go to `https://localhost:8181/hawtio` and login to Keycloak as `admin` or `viewer` to see Hawtio admin console. If you login as `jdoe`, you should receive "forbidden" error in Hawtio.

== WildFly

Assume `$JBOSS_HOME` is the root directory of your WildFly/JBoss EAP installation and you deployed Hawtio WAR to it as described in xref:get-started.adoc[].

Install Keycloak adapter subsystem to your WildFly as described on the https://www.keycloak.org/docs/latest/securing_apps/index.html#_jboss_adapter[Keycloak documentation].

Download and copy `keycloak-hawtio.json` and `keycloak-bearer.json` from https://github.com/hawtio/hawtio/tree/master/examples/keycloak-integration[this example] into WildFly. File `keycloak-bearer.json` is currently used for adapters on server (JAAS Login module) side. File `keycloak-hawtio.json` is used on client (Hawtio JS application) side.

[source,console]
----
cp examples/keycloak-integration/keycloak-hawtio.json $JBOSS_HOME/standalone/configuration/
cp examples/keycloak-integration/keycloak-bearer.json $JBOSS_HOME/standalone/configuration/
----

In `$JBOSS_HOME/standalone/configuration/standalone.xml` configure system properties like this:

[source,xml]
----
<extensions>
  ...
</extensions>

<system-properties>
  <property name="hawtio.authenticationEnabled" value="true" />
  <property name="hawtio.realm" value="hawtio" />
  <property name="hawtio.roles" value="admin,manager,viewer" />
  <property name="hawtio.rolePrincipalClasses" value="org.keycloak.adapters.jaas.RolePrincipal" />
  <property name="hawtio.keycloakEnabled" value="true" />
  <property name="hawtio.keycloakClientConfig" value="${jboss.server.config.dir}/keycloak-hawtio.json" />
  <property name="hawtio.keycloakServerConfig" value="${jboss.server.config.dir}/keycloak-bearer.json" />
</system-properties>
----

Also add `hawtio` realm to this file in `<security-domains>` section:

[source,xml]
----
<security-domain name="hawtio" cache-type="default">
  <authentication>
    <login-module code="org.keycloak.adapters.jaas.BearerTokenLoginModule" flag="required">
      <module-option name="keycloak-config-file" value="${hawtio.keycloakServerConfig}"/>
    </login-module>
  </authentication>
</security-domain>
----

Add the `<secure-deployment>` section to the `keycloak` subsystem in `$JBOSS_HOME/standalone/configuration/standalone.xml`. It should ensure that Hawtio WAR is able to find the JAAS login modules.

[source,xml]
----
<subsystem xmlns="urn:jboss:domain:keycloak:1.1">
  <secure-deployment name="hawtio.war">
    <resource>does-not-matter</resource>
    <auth-server-url>does-not-matter</auth-server-url>
  </secure-deployment>
</subsystem>
----

Run WildFly on port `8080` and go to `http://localhost:8080/hawtio`. Users are again `admin` and `viewer` with access and `jdoe` without access.

== Jetty

Assume `$JETTY_HOME` is the root directory of your Jetty installation and you deployed Hawtio WAR to Jetty as described in xref:get-started.adoc[].

Install Keycloak Jetty adapter into your Jetty server as described on the https://www.keycloak.org/docs/latest/securing_apps/index.html#_jetty9_adapter[Keycloak documentation].

Download and copy `keycloak-hawtio.json` and `keycloak-bearer.json` into Jetty. File `keycloak-bearer.json` is currently used for adapters on server (JAAS Login module) side. File `keycloak-hawtio.json` is used on client (Hawtio JS application) side.

[source,console]
----
cp examples/keycloak-integration/keycloak-hawtio.json $JETTY_HOME/etc/
cp examples/keycloak-integration/keycloak-bearer.json $JETTY_HOME/etc/
----

Create file `$JETTY_HOME/etc/login.conf` with the content like this:

[source,java]
----
hawtio {
    org.keycloak.adapters.jaas.BearerTokenLoginModule required
        keycloak-config-file="${hawtio.keycloakServerConfig}";
};
----

Export `JETTY_HOME` in your terminal. For example:

[source,shell]
----
export JETTY_HOME=/mydir/jetty-distribution-9.x.x
----

Export `JAVA_OPTIONS` and add all necessary system properties similarly like this:

[source,shell]
----
export JAVA_OPTIONS="-Dhawtio.authenticationEnabled=true \
                     -Dhawtio.realm=hawtio \
                     -Dhawtio.keycloakEnabled=true \
                     -Dhawtio.roles=admin,manager,viewer \
                     -Dhawtio.rolePrincipalClasses=org.keycloak.adapters.jaas.RolePrincipal \
                     -Dhawtio.keycloakClientConfig=$JETTY_HOME/etc/keycloak-hawtio.json \
                     -Dhawtio.keycloakServerConfig=$JETTY_HOME/etc/keycloak-bearer.json \
                     -Djava.security.auth.login.config=$JETTY_HOME/etc/login.conf"
----

Run Jetty and go to `http://localhost:8080/hawtio`. Users are again `admin` and `viewer` with access and `jdoe` without access.

== Tomcat

Instructions are quite similar to Jetty. You would need to setup JAAS realm and set the system properties. Just use Tomcat adapter instead of the Jetty one. Also you may need to add this system property (really empty value):

[source,java]
----
-Dhawtio.authenticationContainerDiscoveryClasses=
----

This is needed, so that Tomcat will use configured JAAS realm with `BearerTokenLoginModule` instead of `tomcat-users.xml` file, which Hawtio uses on Tomcat by default.
