= Plugins

Hawtio is highly modular, and it includes plugins for different technologies out of the box. Hawtio plugins are essentially https://react.dev/[React] components that are self-contained with all the JavaScript, CSS, and images to make them work. They can utilise Hawtio core features such as authentication and event notification through the Plugin API.

The only requirement for a plugin is to provide the entrypoint that Hawtio can load it from, which must conform to the specification of https://module-federation.io/[Webpack Module Federation].

Hawtio uses JMX to discover which MBeans are present and then dynamically updates the navigation bars and tabs based on what it finds. The UI is updated whenever Hawtio reloads the MBean, which it does periodically or a plugin can trigger explicitly.

Relying on JMX for discovery doesn't mean that plugins can only interact with JMX. They can do anything at all that a browser can, e.g. use REST to discover UI capabilities and other plugins.

== Built-in plugins

The following plugins are all included by default in Hawtio:

[cols="1,5"]
.List of built-in plugins
|===
|Plugin |Description

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/camel[Camel]
a|Adds support for https://camel.apache.org[Apache Camel]. Allows you to browse Camel contexts, routes, endpoints, etc.; visualise running routes and their metrics; create endpoints; send messages; trace message flows; and profile routes to identify which parts runs fast or slow.

Requirements:: A Camel application needs to be running in the JVM. The Camel application needs to include https://camel.apache.org/manual/jmx.html[Camel Management] component to enable JMX. The Source tab requires https://camel.apache.org/components/3.21.x/others/java-xml-jaxb-dsl.html[Camel XML DSL] support. The Debug tab requires https://camel.apache.org/components/3.21.x/others/debug.html[Camel Debug] component. The Trace tab requires enabling of https://camel.apache.org/manual/tracer.html[Camel Tracer].

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/connect[Connect]
a|Allows you to connect to local or remote JVMs.

Requirements:: The Discover tab requires `io.hawt:hawtio-local-jvm-mbean` to the dependencies.

|Diagnostics
|Allows you to control the Java Flight Recorder, see class histogram and access to JVM flags. +
*Not yet ported to v3.*

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/jmx[JMX]
|Provides the core https://www.oracle.com/java/technologies/javase/javamanagement.html[JMX] support for interacting with MBeans, viewing real time attributes, charting, and invoking operations.

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/logs[Logs]
a|Provides support for viewing the logs inside the JVM.

Requirements:: Requires `io.hawt:hawtio-log` and a logging framework-specific implementation for `hawtio-log` to the dependencies. Currently, only `io.hawt:hawtio-log-logback` is provided.

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/quartz[Quartz]
|Allows you to view the status of https://www.quartz-scheduler.org/[Quartz] schedulers and configure them. Also allows you to configure and fire jobs and triggers from the console. If you use https://camel.apache.org/components/3.21.x/quartz-component.html[Camel Quartz] component with your Camel application, this plugin will be automatically enabled.

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/runtime[Runtime]
|Provides general overview of the Java process including threads, system properties, and key metrics.

|https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio/src/plugins/springboot[Spring Boot]
a|Shows information about the Spring Boot application.

Requirements:: Requires Spring Boot https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints[Health, Info, Loggers, and HTTP Exchanges endpoints] to be exposed to activate each corresponding tab in the plugin.
|===
