= Hawtio Architecture

This page presents general information about Hawtio architecture. We show all the components (client, server, agent connections). For details about plugin development, see xref::developers/plugins.adoc[].

== Hawtio React Single Page Application

Repository: https://github.com/hawtio/hawtio-next

There are two main _parts_ of this repository:

* https://github.com/hawtio/hawtio-next/tree/main/packages/hawtio[@hawtio/react] NPM package which is a consumable Hawtio package with all Hawtio React components, services and APIs
* https://github.com/hawtio/hawtio-next/tree/main/app[Hawtio application] which is _sample application_ that uses the above package. Similar application is available in https://github.com/hawtio/hawtio/tree/4.x/console[Hawtio console application] (used in Hawtio WAR and distributed as Java deployable application).

Why the distinction?

`@hawtio/react` package is pure JavaScript/TypeScript _library_ bundled with https://tsup.egoist.dev/[`tsup`] and distributed as https://www.npmjs.com/package/@hawtio/react[NPM package]

`app` application is using this package and is bundled as _application_ using https://webpack.js.org[Webpack].

=== What are the elements of `@hawtio/react` package?

`@hawtio/react` package is reusable _library_ that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export[exports] JavaScript values/functions/classes. We can groups these exported elements into two categories:

* React components - should be imported from `.tsx` files and simply used with https://react.dev/learn/writing-markup-with-jsx[JSX] syntax. Most of the components use https://v5-archive.patternfly.org/[Patternfly V5 library], but there are few pure React/HTML components
* JavaScript variables, functions and classes, as well as TypeScript type aliases, interfaces and enumerations. +
Hawtio services (core services, plugin management, user management, ...) are exported as variables which are instances of Hawtio classes.

The most important Hawtio React/Patternfly component is `<Hawtio>` which is full page with headers, sidebars and content areas. The UI built by `<Hawtio>` component depends on registered plugins.

Hawtio includes built-in plugins. See available plugins at xref::plugins.adoc[] page. These plugins are _not_ registered by default. When creating an _application_ based on `@hawtio/react` _library_ we can choose whether to register all or selected Hawtio plugins.

=== How to use `@hawtio/react` package - minimal required setup

In order to _use_ Hawtio client library, you should create an application similar to https://github.com/hawtio/hawtio-next/tree/main/app[Hawtio application].

At minimum we should use these files:

`index.ts`:

[source,javascript]
----
import '@hawtio/react/dist/index.css'
import '@patternfly/react-core/dist/styles/base.css'

import('./bootstrap')
----

`bootstrap.tsx`:

[source,javascript]
----
import React from 'react'
import ReactDOM from 'react-dom/client'

import { Hawtio } from '@hawtio/react/ui'
import { hawtio } from '@hawtio/react'

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement)

hawtio.bootstrap().then(() => {
    root.render(
      <React.StrictMode>
        <Hawtio />
      </React.StrictMode>,
    )
})
----

NOTE:: The separation is required because of webpack Module Federation and usage of shared packages. See https://webpack.js.org/concepts/module-federation/#uncaught-error-shared-module-is-not-available-for-eager-consumption[the details here].

This setup is almost pure React application where two steps are required

* Call `ReactDOM.createRoot` to obtain _root element_
* Render `<Hawtio>` React component for this root element

The only difference is that we need to call `hawtio.bootstrap()` function which initializes internal Hawtio services.

As you can see, rendering React component is performed after resolving the promise returned from `hawtio.bootstrap()` - this allows synchronization with Hawtio, so components are rendered after fully initializing Hawtio.

To learn more about stages of Hawtio initialization and how plugins are registered, read the full example below.

=== How to use `@hawtio/react` package - full setup

Because Hawtio _application_ should be bundled by Webpack, it is important to be aware of how such application is bundled. Without going into details, Webpack allows to split all reachable JavaScript code into https://webpack.js.org/guides/code-splitting/[chunks]. Ideally, when Single Page Application starts, only necessary JavaScript code is fetched and evaluated, while remaining code is loaded on demand.

JavaScript supports two kind of _module imports_:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import[static import]. With `import ... from module-name` statement, we effectively include the imported module into the importing module.
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import[dynamic import]. With `import('module-name')` we can use the module asynchronously - `import()` operator returns a Promise resolved only when the imported code is loaded and evaluated.

While browsers support ESM modules and both of these _import_ versions, Webpack transpiles this code into more web-optimized version, while keeping the sync/async semantics of `import` and `import()`.

The thing is that Hawtio _application_ (which uses `@hawtio/react` _library_) should carefully choose between static and dynamic imports.

`@hawtio/react` uses Node.js https://nodejs.org/api/packages.html#subpath-exports[subpath exports] for explicit specification of what can be imported from this package. Here's the relevant `package.json` fragment:

[source,json]
----
"exports": {
  ".": {
    "types": "./dist/index.d.ts",
    "require": "./dist/index.js",
    "default": "./dist/index.js"
  },
  "./init": {
    "types": "./dist/init.d.ts",
    "require": "./dist/init.js",
    "default": "./dist/init.js"
  },
  "./ui": {
    "types": "./dist/ui/index.d.ts",
    "require": "./dist/ui/index.js",
    "default": "./dist/ui/index.js"
  },
  "./dist/index.css": {
    "default": "./dist/index.css"
  }
},
----

Focusing on JavaScript only, we can import three distinct module locations:

* `"@hawtio/react"`: this is the entry point with packages containing all Hawtio services, but no React (or Patternfly) components
* `"@hawtio/react/init"`: this is the entry point that contains initialization code and single `<HawtioInitialization>` React component which doesn't rely on Patternfly
* `"@hawtio/react/ui"`: this is the entry point with React/Patternfly components, of which the most important is `<Hawtio>`

How to import these packages?

An _application_ that launches by rendering `<Hawtio>` component should use the above entry points in the following way:

From `@hawtio/react/init` we can statically import `hawtio`, `configManager` and `<HawtioInitialization>` component
to show initialization UI before importing full package:

[source,typescript]
----
import ReactDOM from 'react-dom/client'

import { configManager, hawtio, HawtioInitialization, TaskState } from '@hawtio/react/init'

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement)

root.render(<HawtioInitialization verbose />)

configManager.addProductInfo('Test App', '1.0.0')
hawtio.addUrl('plugin')
...
----

`@hawtio/react` should be imported dynamically, so we can bootstrap it asynchronously:

[source,typescript]
----
import('@hawtio/react').then(async m => {
  // Register all default Hawtio plugins
  m.registerPlugins()

  m.hawtio.bootstrap().then(() => {
    // ...
  })
})
----

Finally within `.then` block of the promise returned by `hawtio.bootstrap()` we can dynamically import the UI packages
of Hawtio and render `<Hawtio>` component:
[source,typescript]
----
m.hawtio.bootstrap().then(() => {
  import('@hawtio/react/ui').then(m => {
    root.render(
      <React.StrictMode>
        <m.Hawtio />
      </React.StrictMode>
    )
  })
})
----

More information about writing Hawtio applications and plugins (including more information about how to register custom or built-in plugins) can be found at xref::plugins.adoc[].

== Hawtio server

Repository: https://github.com/hawtio/hawtio

This repository was used since early 1.x release. Back in these days, the web application was a single Maven module that produced Java WAR application. The rest of the modules were about integration with Jolokia and implementation of security filters, additional JMX MBeans and things like Git facade (for Fabric8).

In Hawtio 4 this is still a very important project, which also includes a WAR application (that uses `@hawtio/react` NPM package), but there are more deployment options. We have also removed the stuff required by Fabric8 and OSGi.

When describing xref:#_hawtio_react_single_page_application[], we didn't mention https://jolokia.org/[Jolokia] at all, but this is very important part of Hawtio's identity.

Hawtio _server_ is effectively a server-side web application that exposes Jolokia Agent REST API, which is then used by Hawtio _client_ JMX plugin.

There are 3 ways to _start_ (or _deploy_) such Hawtio server:

* WAR, which can be deployed to any standard Servlet container (Tomcat, Jetty, Wildfly, ...)
* Spring Boot application, which uses https://docs.spring.io/spring-boot/reference/web/servlet.html#web.servlet.embedded-container[Spring Boot managed web server]
* https://quarkus.io/guides/web[Quarkus web application] based on https://vertx.io/[Vert.x].

Whatever the deployment method, Hawtio server exposes several endpoints that support Hawtio _client_ application. These endpoints may be provided by other means (server-side Node.js application, as in Hawtio Online), so _this_ Hawtio server is optional.

The most important _endpoint_ exposed is Jolokia endpoint, which gives Hawtio client application a _view_ into JVM's MBeans. Remember that many plugins like `camel()` or `jmx()` simply won't work without Jolokia.

== Remote Jolokia agents

Finally we need to describe a part of Hawtio picture that allows:

* Hawtio client to access Jolokia agent available from _different_ JVM than the one which serves the resources of Hawtio client
* Hawtio server to act as a proxy between Hawtio client and remote Jolokia Agent.

Remote Jolokia agents are JVM applications (like Camel JBang applications or Apache Artemis brokers with Jolokia agent enabled) which don not include embedded Hawtio applications, but may be used through Hawtio proxy.

Again, knowing the history helps to understand this part of the picture. When Hawtio was originally created, Jolokia project existed already for a while, but never had full UI support - it was purely a REST API exposing MBeans from running JVM application.

Hawtio with its usage of Angular and JQuery Ajax was built to access these Jolokia agents and their REST APIs, so real browser UI could be build.
