site:
  title: Hawtio
  url: https://hawt.io
  #start_page: docs::index.adoc

content:
  sources:
    - url: .
      branches: HEAD

asciidoc:
  attributes:
    table-stripes: even

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
