= Camel

The Camel plugin adds support for https://camel.apache.org[Apache Camel]. It allows you to browse Camel contexts, routes, endpoints, etc.; visualise running routes and their metrics; create endpoints; send messages; trace message flows; and profile routes to identify which parts runs fast or slow.

== Requirements

A Camel application needs to be running in the JVM, which needs to include https://camel.apache.org/manual/jmx.html[Camel Management] component to enable JMX.

=== Source

The Source tab requires https://camel.apache.org/components/3.21.x/others/java-xml-jaxb-dsl.html[Camel XML DSL] support.

=== Debug

The Debug tab requires https://camel.apache.org/components/3.21.x/others/debug.html[Camel Debug] component.

=== Trace

The Trace tab requires enabling of https://camel.apache.org/manual/tracer.html[Camel Tracer].

=== Exchanges

To enable browsing of inflight exchanges in the **Exchanges** tab, the following Camel Main option needs to be enabled:

[source,java]
.`application.properties`
----
camel.main.inflight-repository-browse-enabled = true
----

=== Endpoints (in/out)

To activate the **Endpoints (in/out)** tab, either or both of the following Camel Main options need to be enabled:

[source,java]
.`application.properties`
----
camel.main.endpoint-runtime-statistics-enabled = true
camel.main.jmx-management-statistics-level = Extended
----

== Usage

Click the Camel tab in the top navigation bar to view the running Camel Context in the current JVM.
The selection will not appear on the navigation bar if there is no Camel Context running.

The Camel plugin allows you to view all the running Camel applications in the current JVM.
You can among others see the following details:

- Lists of all running Camel applications
- Detailed information of each Camel Context such as Camel version number, runtime statics
- Lists of all routes in each Camel applications and their runtime statistics
- Manage the lifecycle of all Camel applications and their routes, so you can restart / stop / pause / resume, etc.
- Graphical representation of the running routes along with real time metrics
- Live tracing and debugging of running routes
- Profile the running routes with real time runtime statics; detailed specified per processor
- Browsing and sending messages to Camel endpoint

== Source

https://github.com/hawtio/hawtio-react/tree/main/packages/hawtio/src/plugins/camel
