name: Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'modules/**'
      - 'src/**'
      - 'supplemental-ui/**'
      - 'static/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure git
        run: |
          GIT_USER_NAME="github-actions[bot]"
          GIT_USER_EMAIL=41898282+github-actions[bot]@users.noreply.github.com
          git config --local user.email "$GIT_USER_EMAIL"
          git config --local user.name "$GIT_USER_NAME"
      - name: Deploy
        run: |
          yarn install
          yarn build
          # docs/ is the only other directory than root that GitHub Pages recognises
          rm -rf docs/ && mv public docs
          git add docs/
          git commit -m 'chore: deploy website'
          git push origin main
