name: deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'static/**'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        run: |
          sudo apt-get install -y git nodejs
          sudo npm install --global yarn
      - name: Deploy
        run: |
          yarn install
          yarn deploy
          git add docs/
          git commit -m 'core: deploy website'
          git push origin main
