name: Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'static/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure git
        run: |
          GIT_USER_NAME="github-actions[bot]"
          GIT_USER_EMAIL=41898282+github-actions[bot]@users.noreply.github.com
          git config --local user.email "$GIT_USER_EMAIL"
          git config --local user.name "$GIT_USER_NAME"
      - name: Deploy
        run: |
          yarn install
          yarn deploy
          git add docs/
          git commit -m 'chore: deploy website'
          git push origin main
